Configuration reading/handling
tinker-engine/sailon-protocols pull request #1
Opened 2021-01-05 18:12 UTC by nrsyed

This PR removes the scriptconfig dependency found in the legacy sailon_client and introduces a default configuration that is updated with values from a dictionary or from a file in `ONDProtocol.__init__`. Because configuration handling will ultimately be the responsibility of tinker engine, the goal of this PR is only to provide a simple method for reading the existing configuration format without additional dependencies; it is not intended to be a robust means of configuration handling.

2021-01-05 19:34 UTC, waxlamp requested changes
This seems like a bit of a work-in-progress, which is fine; by that metric this looks good to me. There's a minor typo that you may want to fix.

Since you're starting out with a static config here, a good next step might be simply to use the config mechanism of Tinker Engine instead of setting it up in-band this way. Let me know if that makes sense.

2021-01-05 19:34 UTC, waxlamp commented on ond/ond.py
> +    protcol = ONDProtocol(None, None)
```suggestion
    protocol = ONDProtocol(None, None)
```

2021-01-14 02:04 UTC, nrsyed commented
@waxlamp I've revamped this branch so that it imports the current iteration of tinker engine and leverages its config handling, like you suggested. This should simplify things considerably.

2021-01-14 15:34 UTC, waxlamp commented
> @waxlamp I've revamped this branch so that it imports the current iteration of tinker engine and leverages its config handling, like you suggested. This should simplify things considerably.

Cool. Is this ready for a review then?

2021-01-14 16:03 UTC, nrsyed commented
> > @waxlamp I've revamped this branch so that it imports the current iteration of tinker engine and leverages its config handling, like you suggested. This should simplify things considerably.
> 
> Cool. Is this ready for a review then?

Yep, it is.

2021-01-14 20:43 UTC, waxlamp approved these changes

2021-01-15 01:29 UTC, merged