Save features and load saved features
tinker-engine/sailon-protocols pull request #16
Opened 2021-05-06 16:16 UTC by nrsyed

@waxlamp @cfunk1210 @as6520 

This PR adds functionality for using saved features from the feature extraction step.

2021-05-06 17:00 UTC, as6520 requested changes

2021-05-06 17:00 UTC, as6520 commented on ond.py
> +                "image_features": {},
This should be renamed to `features` since we use it for videos too.

2021-05-06 17:00 UTC, as6520 commented on ond.py
> +                        if config["feature_extraction_only"]:
I don't think it is necessary to have `feature_extraction_only` inside the `save_features`.

2021-05-21 21:17 UTC, nrsyed commented on ond.py
> +                "image_features": {},
Updated in the latest commit.

2021-05-21 21:18 UTC, nrsyed commented on ond.py
> +                        if config["feature_extraction_only"]:
Good catch, I think the check for `feature_extraction_only` should exist at the same indentation level as the check for `save_features`?

2021-05-24 14:29 UTC, as6520 commented on ond.py
> +                        if config["feature_extraction_only"]:
yes, looked at the most recent commit and it looks good

2021-05-25 16:59 UTC, merged